from collections.abc import Callable, Hashable
from types import UnionType
from typing import Any, Self, final

from ....tools.types.general import floatOrInt
from ...runners.converters.color_converter import ColorConverter
from ...runners.converters.converter import Converter
from .template_enums import Flags, UIGroups, UITypes


@final
class AppLibUndefinedType:
    """A type used as a sentinel for undefined values."""

    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: Any) -> Self: ...


type AppLibUndefined = AppLibUndefinedType
type Validator = Callable | CompatilityValidator


class GUIMessage:
    def __init__(self, title: str, description: str = ""):
        """
        A message informing the user of something.

        Parameters
        ----------
        title : str
            The title of the message.
        description : str, optional
            The description (or content) of the message.
            By default "".
        """
        self.title = title
        self.description = description


class CompatilityValidator:
    def __init__(self, validator: Callable, fields: list[str]) -> None:
        self.validator = validator
        self.fields = fields


class Option:
    def __init__(
        self,
        default: Any,
        actions: Callable | list[Callable] = AppLibUndefined,
        converter: Converter = AppLibUndefined,
        flags: Flags | list[Flags] = AppLibUndefined,
        max: floatOrInt | None = AppLibUndefined,
        min: floatOrInt | None = AppLibUndefined,
        type: type | UnionType = AppLibUndefined,
        ui_disable_button: bool = AppLibUndefined,
        ui_disable_other: Any = AppLibUndefined,
        ui_disable_self: Any = AppLibUndefined,
        ui_file_filter: str | None = AppLibUndefined,
        ui_group: Hashable | list[Hashable] = AppLibUndefined,
        ui_group_parent: UIGroups | list[UIGroups] = AppLibUndefined,
        ui_info: GUIMessage = AppLibUndefined,
        ui_invalid_input: GUIMessage = AppLibUndefined,
        ui_show_dir_only: bool = AppLibUndefined,
        ui_type: UITypes = AppLibUndefined,
        ui_unit: str = AppLibUndefined,
        validators: Validator | list[Validator] = AppLibUndefined,
        values: list | dict = AppLibUndefined,
    ):
        """
        Create an option instance usable in a GUI environment.

        An Option is the value of a setting, as defined in the template specification.

        Parameters
        ----------
        default : Any
            The default value for this setting.
            ##### Applicable settings: All
        actions : Callable | list[Callable], optional
            Functions to call when this setting changes value.
            Each function must take one argument, which is the new value of this setting.
            ##### Applicable settings: All
        converter : Converter, optional
            The value converter used to convert values between config and GUI representation.
            ##### Applicable settings: All
        flags : Flags | list[Flags], optional
            Special flags that apply to this setting.
            ##### Applicable settings: All
        max : floatOrInt, optional
            The maximum value for this setting.
            If None, there is no limit. Although upper limit is 2147483647 (2.1 billion) in the GUI.
            ##### Applicable settings: Any number ranges (e.g. slider or spinbox)
            NOTE: Sliders do not support floats currently.
        min : floatOrInt, optional
            The minimum value for this setting.
            If None, there is no limit. Although lower limit is -2147483648 (-2.1 billion) in the GUI.
            ##### Applicable settings: Any number ranges (e.g. slider or spinbox)
            NOTE: Sliders do not support floats currently.
        type : type | UnionType, optional
            The Python type for the value of this setting. For instance, 3 has type 'int'.

            The final type is a union of:
            - default
            - type
            ##### Applicable settings: All
        ui_disable_button : bool, optional
            Enable or disable the disable button for this setting.
            ##### Applicable settings: All
            NOTE: A disable button is generated by default if `ui_disable_self` is defined.
            NOTE: If `ui_disable_self` is Undefined, the disable button will only disable this setting in the GUI.
        ui_disable_children : Any, optional
            The value which disables children of this setting.
            This value is used in validation if it is the smallest of all other values (e.g. default, min).

            Please ensure that the backend using this setting respects this value - otherwise it has no effect.
            ##### Applicable settings: All
        ui_disable_self : Any, optional
            The value which disables this setting.
            This value is used in validation if it is the smallest of all other values (e.g. default, min).

            Please ensure that the backend using this setting respects this value - otherwise it has no effect.
            In the GUI, a button for disabling this setting is provided.
            ##### Applicable settings: All
        ui_file_filter : str, optional
            Only files matching this filter are shown.
            If None, all files are shown.
            If you want multiple filters, seperate them with ;;

            For instance:
            ```
            "Images (*.png *.xpm *.jpg);;Text files (*.txt);;XML files (*.xml)"
            ```
            ##### Applicable settings: File Selectors
        ui_group : Hashable | list[Hashable], optional
            Designate a group ID (GID) which all options with this GID belongs to.
            This makes various actions possible for settings, e.g., they can be visually grouped in the GUI.

            A valid GID can be either:
            - str: "id_1, id_2 ,..., id_n"
            - Hashable: Any hashable object, e.g. 0
            - list[Hashable]: A list of hashable objects that follows the ordering of a str GID

            The ordering of a str GID is as follows:
            - This setting belongs to the group at id_1.
            - Any subsequent GIDs are children of this setting's group.

            ##### Applicable settings: All
        ui_group_parent : UIGroups | list[UIGroups], optional
            Designate the parent setting of a group.

            All groups must have a parent and only one setting in each group can be designated parent.
            If more than one exist, the first found is used.
            ##### Applicable settings: All
            NOTE: Full documentation is available at #LINK: src\\applib\\module\\configuration\\tools\\template_options\\template_docs.txt
        ui_info : GUIMessage, optional
            The title and description of this setting in the GUI.
            ##### Applicable settings: All
        ui_invalid_input : GUIMessage, optional
            Message informing the user that they typed invalid data into this setting in the GUI.
            ##### Applicable settings: Any free-form input, e.g., a line edit.
        ui_show_dir_only : bool, optional
            Only show directories. `ui_file_filter` is ignored.
            ##### Applicable settings: File Selectors
        ui_type : UITypes, optional
            The widget type to use for this setting.
            ##### Applicable settings: All
        ui_unit : str, optional
            The unit associated with this setting.
            ##### Applicable settings: Slider (TODO: Ensure units can be used on all GUI elements)
            NOTE: Must be singular, i.e., "day".
        validators : Validator | list[Validator], optional
            Functions used to validate the value of this setting (in addition to default Pydantic validation).
            Each function must take one argument, which is the value of this Option.
            If the value is invalid, they must raise a ValueError.
        values : list | dict, optional
            Possible values for this setting.
            ##### Applicable settings: Combobox
        """
        self.actions = actions
        self.converter = converter
        self.default = default
        self.max = max
        self.min = min
        self.type = type
        self.ui_disable_button = ui_disable_button
        self.ui_disable_children = ui_disable_children
        self.ui_disable_self = ui_disable_self
        self.ui_file_filter = ui_file_filter
        self.flags = flags
        self.ui_group = ui_group
        self.ui_group_parent = ui_group_parent
        self.ui_info = ui_info
        self.ui_invalid_input = ui_invalid_input
        self.ui_show_dir_only = ui_show_dir_only
        self.ui_type = ui_type
        self.ui_unit = ui_unit
        self.validators = validators
        self.values = values

    def __getattr__(self, name):
        """
        Called when the default attribute access fails with an AttributeError (either __getattribute__()
        raises an AttributeError because `name` is not an instance attribute or an attribute in the class tree
        for self; or __get__() of a `name` property raises AttributeError)
        """
        return AppLibUndefined

    def __repr__(self) -> str:
        return f"{self.__class__.__name__} {{default={self.default}, type={self.type}, values={self.values}}}"

    def __str___(self) -> str:
        return repr(self)

    def defined(self, attr_value) -> bool:
        """Returns True if the given attribute is defined."""
        return attr_value != AppLibUndefined


class FileSelectorOption(Option):
    def __init__(
        self,
        default: str,
        actions: Callable | list[Callable] = AppLibUndefined,
        converter: Converter = AppLibUndefined,
        flags: Flags | list[Flags] = AppLibUndefined,
        type: type | UnionType = AppLibUndefined,
        ui_disable_button: bool = AppLibUndefined,
        ui_disable_children: Any = AppLibUndefined,
        ui_disable_self: Any = AppLibUndefined,
        ui_file_filter: str | None = None,
        ui_group: Any | list[Any] = AppLibUndefined,
        ui_group_parent: UIGroups | list[UIGroups] = AppLibUndefined,
        ui_info: GUIMessage = AppLibUndefined,
        ui_show_dir_only: bool = False,
        ui_type: UITypes = UITypes.FILE_SELECTION,
        validators: Validator | list[Validator] = AppLibUndefined,
        **kwargs,
    ):
        super().__init__(
            default=default,
            actions=actions,
            converter=converter,
            type=type,
            ui_disable_button=ui_disable_button,
            ui_disable_children=ui_disable_children,
            ui_disable_self=ui_disable_self,
            ui_file_filter=ui_file_filter,
            flags=flags,
            ui_group=ui_group,
            ui_group_parent=ui_group_parent,
            ui_info=ui_info,
            ui_show_dir_only=ui_show_dir_only,
            ui_type=ui_type,
            validators=validators,
            **kwargs,
        )


COLOR_CONVERTER = ColorConverter()


class ColorPickerOption(Option):
    def __init__(
        self,
        default: str,
        actions: Callable | list[Callable] = AppLibUndefined,
        converter: Converter = COLOR_CONVERTER,
        flags: Flags | list[Flags] = AppLibUndefined,
        type: type | UnionType = AppLibUndefined,
        ui_disable_button: bool = AppLibUndefined,
        ui_disable_children: Any = AppLibUndefined,
        ui_disable_self: Any = AppLibUndefined,
        ui_group: Hashable | list[Hashable] = AppLibUndefined,
        ui_group_parent: UIGroups | list[UIGroups] = AppLibUndefined,
        ui_info: GUIMessage = AppLibUndefined,
        ui_type: UITypes = UITypes.COLOR_PICKER,
        validators: Validator | list[Validator] = AppLibUndefined,
        **kwargs,
    ):
        super().__init__(
            default=default,
            actions=actions,
            converter=converter,
            type=type,
            ui_disable_button=ui_disable_button,
            ui_disable_children=ui_disable_children,
            ui_disable_self=ui_disable_self,
            flags=flags,
            ui_group=ui_group,
            ui_group_parent=ui_group_parent,
            ui_info=ui_info,
            ui_type=ui_type,
            validators=validators,
            **kwargs,
        )


class ComboBoxOption(Option):
    def __init__(
        self,
        default,
        values: list | dict,
        actions: Callable | list[Callable] = AppLibUndefined,
        converter: Converter = AppLibUndefined,
        flags: Flags | list[Flags] = AppLibUndefined,
        max: floatOrInt | None = AppLibUndefined,
        min: floatOrInt | None = AppLibUndefined,
        type: type | UnionType = AppLibUndefined,
        ui_disable_button: bool = AppLibUndefined,
        ui_disable_children: Any = AppLibUndefined,
        ui_disable_self: Any = AppLibUndefined,
        ui_group: Any | list[Any] = AppLibUndefined,
        ui_group_parent: UIGroups | list[UIGroups] = AppLibUndefined,
        ui_info: GUIMessage = AppLibUndefined,
        ui_type: UITypes = UITypes.COMBOBOX,
        validators: Validator | list[Validator] = AppLibUndefined,
        **kwargs,
    ):
        super().__init__(
            default=default,
            values=values,
            actions=actions,
            converter=converter,
            min=min,
            max=max,
            type=type,
            ui_disable_button=ui_disable_button,
            ui_disable_children=ui_disable_children,
            ui_disable_self=ui_disable_self,
            flags=flags,
            ui_group=ui_group,
            ui_group_parent=ui_group_parent,
            ui_info=ui_info,
            ui_type=ui_type,
            validators=validators,
            **kwargs,
        )


class TextEditOption(Option):
    def __init__(
        self,
        default: str,
        actions: Callable | list[Callable] = AppLibUndefined,
        converter: Converter = AppLibUndefined,
        flags: Flags | list[Flags] = AppLibUndefined,
        type: type | UnionType = AppLibUndefined,
        ui_disable_button: bool = AppLibUndefined,
        ui_disable_children: Any = AppLibUndefined,
        ui_disable_self: Any = AppLibUndefined,
        ui_group: Any | list[Any] = AppLibUndefined,
        ui_group_parent: UIGroups | list[UIGroups] = AppLibUndefined,
        ui_info: GUIMessage = AppLibUndefined,
        ui_invalid_input: GUIMessage = AppLibUndefined,
        ui_type: UITypes = UITypes.LINE_EDIT,
        validators: Validator | list[Validator] = AppLibUndefined,
        **kwargs,
    ):
        super().__init__(
            default=default,
            actions=actions,
            converter=converter,
            type=type,
            ui_disable_button=ui_disable_button,
            ui_disable_children=ui_disable_children,
            ui_disable_self=ui_disable_self,
            flags=flags,
            ui_group=ui_group,
            ui_group_parent=ui_group_parent,
            ui_info=ui_info,
            ui_invalid_input=ui_invalid_input,
            ui_type=ui_type,
            validators=validators,
            **kwargs,
        )


class NumberOption(Option):
    def __init__(
        self,
        default: floatOrInt,
        actions: Callable | list[Callable] = AppLibUndefined,
        converter: Converter = AppLibUndefined,
        flags: Flags | list[Flags] = AppLibUndefined,
        min: floatOrInt | None = None,
        max: floatOrInt | None = None,
        type: type | UnionType = AppLibUndefined,
        ui_disable_button: bool = AppLibUndefined,
        ui_disable_children: Any = AppLibUndefined,
        ui_disable_self: Any = AppLibUndefined,
        ui_group: Any | list[Any] = AppLibUndefined,
        ui_group_parent: UIGroups | list[UIGroups] = AppLibUndefined,
        ui_info: GUIMessage = AppLibUndefined,
        ui_type: UITypes = AppLibUndefined,
        ui_unit: str = AppLibUndefined,
        validators: Validator | list[Validator] = AppLibUndefined,
        **kwargs,
    ):
        super().__init__(
            default=default,
            actions=actions,
            converter=converter,
            max=max,
            min=min,
            type=type,
            ui_disable_button=ui_disable_button,
            ui_disable_children=ui_disable_children,
            ui_disable_self=ui_disable_self,
            flags=flags,
            ui_group=ui_group,
            ui_group_parent=ui_group_parent,
            ui_info=ui_info,
            ui_type=ui_type,
            ui_unit=ui_unit,
            validators=validators,
            **kwargs,
        )
