import shlex
from argparse import ArgumentParser, Namespace, RawTextHelpFormatter, _ArgumentGroup
from typing import overload

from ...configuration.tools.search import SEARCH_SEP, SearchMode
from ...tools.types.config import AnyConfig
from ...tools.types.templates import AnyTemplate
from .template_utils.options import Option

# TODO: Inspiration from:

# General
# https://docs.pydantic.dev/latest/api/pydantic_settings/#pydantic_settings.CliApp.run
# https://docs.pydantic.dev/latest/concepts/pydantic_settings/#integrating-with-existing-parsers
# https://docs.pydantic.dev/latest/concepts/pydantic_settings/#cli-boolean-flags
# https://docs.pydantic.dev/latest/concepts/pydantic_settings/#cli-boolean-flags


# Serializing
# # https://docs.python.org/3/library/argparse.html#argument-groups
# https://stackoverflow.com/a/72741664 (nice example using serialize to construct argparser)
# https://docs.pydantic.dev/latest/concepts/serialization/#iterating-over-models


# Deserializing
# https://github.com/swansonk14/typed-argument-parser?tab=readme-ov-file#argument-processing
class CLIArguments:
    def __init__(self):
        pass

    @overload
    def create_argparser(
        self,
        from_value: AnyTemplate,
        name: str | None = None,
        version: str = "UNKNOWN VERSION",
    ) -> ArgumentParser: ...
    @overload
    def create_argparser(
        self,
        from_value: AnyConfig,
        name: str | None = None,
        version: str = "UNKNOWN VERSION",
    ) -> ArgumentParser: ...

    def create_argparser(
        self, from_value, name: str | None = None, version: str = "UNKNOWN VERSION"
    ) -> ArgumentParser:
        """
        Create an argument parser from a template.

        Useful for generating a command-line interface (CLI).

        Parameters
        ----------
        from_value
            The value to create an argument parser from.
        name
            The program name. If None, the name is automatically inferred. By default None.

        version
            The program version. By default None.

        Returns
        -------
        ArgumentParser
            The argument parser generated by `from_value`.
        """
        if isinstance(from_value, AnyTemplate):
            template = from_value
        elif isinstance(from_value, AnyConfig):
            template = from_value.template
        else:
            raise TypeError(
                f"cannot create an argument parser from input '{from_value}'. Expected one of: {', '.join([f'{type(AnyTemplate).__name__}', f'{type(AnyConfig).__name__}'])}"
            )

        # TODO: Enable "suggest_on_error=True" in Python 3.14
        # TODO: Add proper "usage" message
        parser = ArgumentParser(
            prog=name,
            usage="%(prog)s [options]",
            formatter_class=RawTextHelpFormatter,
        )

        parser.add_argument(
            "--version", action="version", version=f"%(prog)s {version}"
        )

        arg_groups: dict[str, _ArgumentGroup] = {}

        for k, _, path in template.options():
            groups = path.split(SEARCH_SEP)
            if len(groups) > 1 and groups[-1] not in arg_groups:
                arg_groups[groups[-1]] = parser.add_argument_group(groups[-1])

            option: Option = template.get_value(k, path, mode=SearchMode.STRICT)

            if option.defined(option.hide_in_cli) and option.hide_in_cli:
                continue

            # Add help
            if option.defined(option.ui_info):
                help = f"{option.ui_info.title} (default: %(default)s)\n{option.ui_info.description}"
            else:
                help = "(default: %(default)s)"

            # Add multiple choices
            choices = None
            if option.defined(option.values):
                choices = option.values

            # Add formatting
            metavar = None
            if choices:
                if len(choices) > 3:
                    f = f"\n\t{'\n\t'.join([f'{c}' for c in choices])}"
                    metavar = f"{{{f}\n  }}"
                else:
                    f = ", ".join([f"{c}" for c in choices])
                    metavar = f"{{{f}}}"
            elif option.defined(option.type):
                metavar = f"{type(option.default) | option.type}"
            else:
                metavar = f"{type(option.default).__name__}"

            # Add actions
            action = None
            if (
                option.defined(option.type)
                and option.type is bool
                or isinstance(option.default, bool)
            ):
                action = "store_true"

            # Assembly argument list
            arguments = {
                "dest": k,
                "default": option.default,
                "metavar": metavar,
                "help": help,
            }
            if action:
                arguments["action"] = action
                arguments.pop("metavar")
            if choices:
                arguments["choices"] = choices

            # FIXME: This argument handler cannot handle duplicate keys across sections
            try:
                group = arg_groups[groups[-1]]
                # TODO: Add help
                group.add_argument(
                    f"--{k}",
                    **arguments,
                )
            except (KeyError, IndexError):
                parser.add_argument(
                    f"--{k}",
                    **arguments,
                )
        return parser

    def serialize(self, from_config: AnyConfig) -> str:
        """
        Serialize a config to command-line arguments.

        Parameters
        ----------
        from_config : AnyConfig
            The config to serialize.

        Returns
        -------
        list[str]
            A list of shell-escaped command-line arguments.
        """
        args = []

        for k, v, path in from_config.options():
            option: Option = from_config.template.get_value(
                k, path, mode=SearchMode.STRICT
            )

            if option.disable_self:
                continue

            # Must be a bool (not truthy) and must be True
            if v is True:
                args.append(f"--{k}")
            else:
                args.append(f'--{k} "{v}"')

        normalized_str = shlex.join(args)
        return shlex.quote(normalized_str)

    def deserialize(self, args: Namespace, to_config: AnyConfig, merge: bool):
        """
        Deserialize command-line arguments into a config.

        The config's data is overridden with `args`.

        Parameters
        ----------
        args : Namespace
            The command-line arguments to deserialize.
        to_config : type[AnyConfig]
            The model type to deserialize into.
        merge : bool
            If `True`, the command-line arguments are merged into the config.
            Otherwise, a new config is created with default values for
            those not set by command-line args.

        Raises
        ------
        ValidationError
            If `args` could not be deserialized into the model.

        """
        # TODO: Handle list[str]

        if merge:
            to_config.update_config(args)
        else:
            to_config.replace_config(args)
